es/AR/mario/ascii/flac/*.flac usr/share/freeswitch/sounds/es/ar/mario/ascii/flac/
es/AR/mario/digits/flac/*.flac usr/share/freeswitch/sounds/es/ar/mario/digits/flac/
es/AR/mario/misc/flac/*.flac usr/share/freeswitch/sounds/es/ar/mario/misc/flac/
es/AR/mario/time/flac/*.flac usr/share/freeswitch/sounds/es/ar/mario/time/flac/
es/AR/mario/voicemail/flac/*.flac usr/share/freeswitch/sounds/es/ar/mario/voicemail/flac/
